// <auto-generated />
using ExoCaisseEnregistreuse.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExoCaisseEnregistreuse.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExoCaisseEnregistreuse.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Alimentaire"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Vêtements"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Bricolage et jardinage"
                        });
                });

            modelBuilder.Entity("ExoCaisseEnregistreuse.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Prix")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("QteEnStock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.ToTable("Produits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategorieId = 1,
                            Description = "Pour faire de la chantilly bien entendu",
                            ImagePath = "/images/cd0317d6-962a-4a51-9aed-52ee018cd754-placeholder.png",
                            Nom = "Cartouches N2O",
                            Prix = 10.99m,
                            QteEnStock = 45
                        },
                        new
                        {
                            Id = 2,
                            CategorieId = 1,
                            Description = "Le goût des choses simples",
                            ImagePath = "/images/cd0317d6-962a-4a51-9aed-52ee018cd754-placeholder.png",
                            Nom = "Saucisses Herta",
                            Prix = 3.5m,
                            QteEnStock = 48
                        },
                        new
                        {
                            Id = 3,
                            CategorieId = 2,
                            Description = "Composition : 93% Polyester, 7% élasthanne",
                            ImagePath = "/images/cd0317d6-962a-4a51-9aed-52ee018cd754-placeholder.png",
                            Nom = "Chaussettes RC Lens",
                            Prix = 2.25m,
                            QteEnStock = 150
                        });
                });

            modelBuilder.Entity("ExoCaisseEnregistreuse.Models.Produit", b =>
                {
                    b.HasOne("ExoCaisseEnregistreuse.Models.Categorie", "Categorie")
                        .WithMany("ListeProduits")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("ExoCaisseEnregistreuse.Models.Categorie", b =>
                {
                    b.Navigation("ListeProduits");
                });
#pragma warning restore 612, 618
        }
    }
}
